name: Build latex manuscript
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: LaTeX compilation
        uses: dante-ev/latex-action@2021-A
        with:
          working_directory: tex
          root_file: dr17binaries.tex

      - name: Deploy PDF
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tex
          force_orphan: true
